export default {
  TYPE_HABIT_NAME: 'TYPE_HABIT_NAME',
  TYPE_HABIT_DESCRIPTION: 'TYPE_HABIT_DESCRIPTION',
  ADD_HABIT: 'ADD_HABIT',
  DELETE_HABIT: 'DELETE_HABIT',
  EDIT_HABIT: 'EDIT_HABIT',
  DONE_HABIT: 'DONE_HABIT',
  DAY_COUNT: 'DAY_COUNT',
  FILTER_LIST: 'FILTER_LIST',
  OPEN_MODAL: 'OPEN_MODAL',
  CHANGE_CALENDAR: 'CHANGE_CALENDAR',
  COUNT_TIMER: 'COUNT_TIMER',
  SET_TIMER: 'SET_TIMER',
  REGIST_RECORD: 'REGIST_RECORD',
  CHECK_NAME_CHAR_COUNT: 'CHECK_NAME_CHAR_COUNT',
  CHECK_DESCRIPTION_CHAR_COUNT: 'CHECK_DESCRIPTION_CHAR_COUNT',
  RESET_FORM: 'RESET_FORM'
}