export default {
  FIRST_PROCESS: 'FIRST_PROCESS',
  TYPE_HABIT_NAME: 'TYPE_HABIT_NAME',
  TYPE_HABIT_DESCRIPTION: 'TYPE_HABIT_DESCRIPTION',
  ADD_HABIT: 'ADD_HABIT',
  DELETE_HABIT: 'DELETE_HABIT',
  EDIT_HABIT: 'EDIT_HABIT',
  DONE_HABIT: 'DONE_HABIT',
  DAY_COUNT: 'DAY_COUNT',
  FILTER_LIST: 'FILTER_LIST',
  OPEN_AND_CLOSE_MODAL: 'OPEN_AND_CLOSE_MODAL',
  CHANGE_CALENDAR: 'CHANGE_CALENDAR',
  COUNT_TIMER: 'COUNT_TIMER',
  REGIST_RECORD: 'REGIST_RECORD',
  CHECK_NAME_CHAR_COUNT: 'CHECK_NAME_CHAR_COUNT',
  CHECK_DESCRIPTION_CHAR_COUNT: 'CHECK_DESCRIPTION_CHAR_COUNT',
  HIDE_NAME_CHAR_COUNT: 'HIDE_NAME_CHAR_COUNT',
  HIDE_DESCRIPTION_CHAR_COUNT: 'HIDE_DESCRIPTION_CHAR_COUNT',
  RESET_FORM: 'RESET_FORM',
  DELETE_RECORD: 'DELETE_RECORD',
  FINISHED_DAY: 'FINISHED_DAY'
}

export const FILTER_TYPE = {
  ALL: 'all',
  NOT_YET: 'not yet',
  DONE: 'done'
}
